name: Build
on: [push, pull_request]
env:
  CARGO_TERM_COLOR: always
  CARGO_INCREMENTAL: 0
  RUST_BACKTRACE: full
  RUST_LOG: "info"
  RUST_LOG_SPAN_EVENTS: full
  CI_POSTGRES_URI: postgresql://postgres:pass@localhost:5432
  CI_MYSQL_URI: mysql://root:pass@localhost:3306/ci

jobs:
  build:
    name: ${{ matrix.platform }}
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        platform:
          - linux-x64
          - macos-arm64
          - macos-x64
          - windows-x64

        include:
          - platform: linux-x64
            os: ubuntu-latest
          - platform: macos-arm64
            os: macos-14
          - platform: macos-x64
            os: macos-13
          - platform: windows-x64
            os: windows-2022

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Rust toolchain
        uses: dtolnay/rust-toolchain@stable

      - name: Running tests
        run: |
          cargo test --workspace --all-features -- --nocapture
