name: Quick checks
on: [push, pull_request]
env:
  CARGO_TERM_COLOR: always
  RUSTFLAGS: "-D warnings"
  CI_POSTGRES_URI: postgresql://postgres:password@localhost:5432/ci
  CI_MYSQL_URI: mysql://user:password@localhost:3306/ci

jobs:
  check:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Rust toolchain
        uses: dtolnay/rust-toolchain@stable
        with:
          components: "llvm-tools-preview, rustfmt, clippy"

      - name: Check formatting
        run: cargo fmt --all --check

      - name: Running clippy
        run: cargo clippy --all-targets --all-features --examples --tests
