name: Quick checks
on: [push, pull_request]
env:
  CARGO_TERM_COLOR: always
  RUSTFLAGS: "-D warnings"

jobs:
  check:
    runs-on: ubuntu-latest
    steps:
      - name: Install curl & build-essential
        run: apt-get update && apt-get install -y curl build-essential libssl-dev pkg-config

      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Rust toolchain
        uses: dtolnay/rust-toolchain@stable
        with:
          components: "llvm-tools-preview, rustfmt, clippy"

      - name: Check formatting
        run: cargo fmt --all --check

      - name: Running clippy
        run: |
          cargo clippy --all-targets --all-features --examples --tests
