name: Code coverage
on: [push, pull_request]
env:
  CARGO_TERM_COLOR: always
  LLVM_PROFILE_FILE: rsql-%p-%m.profraw
  RUST_BACKTRACE: 1
  RUST_LOG: "info"
  RUST_LOG_SPAN_EVENTS: full
  RUSTFLAGS: -Cinstrument-coverage
  RUSTDOCFLAGS: -Cinstrument-coverage
  CARGO_INCREMENTAL: 0

jobs:
  codecov:
    runs-on: ubuntu-24.04
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Rust toolchain
        uses: dtolnay/rust-toolchain@stable
        with:
          components: "llvm-tools-preview"

      - name: Install grcov
        uses: taiki-e/install-action@main
        with:
          tool: grcov

      - name: Running tests
        run: |
          cargo test --workspace --all-features

      - name: Generate coverage reports
        run: |
          grcov $(find . -name "rsql-*.profraw" -print) \
            -s . \
            --branch \
            --ignore-not-existing \
            --ignore='target/*' \
            --ignore='benches/*' \
            --ignore='/*' \
            --binary-path ./target/debug/ \
            --excl-line='#\[derive' \
            -t lcov \
            -o lcov.info

      - name: Upload coverage reports to Codecov
        uses: codecov/codecov-action@v4.0.1
        with:
          fail_ci_if_error: true
          token: ${{ secrets.CODECOV_TOKEN }}
